eval_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('evaluations/', include('evaluations.urls', namespace='evaluations')),
    path('', include('quizzes.urls', namespace='quizzes')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizzes/urls.py
from django.urls import path
from .views import (
    quiz_view,
    eval_view,
    result_view,
    delete_result,
    # render_pdf_view,
)

app_name = 'quizzes'

urlpatterns = [
    path('', quiz_view, name='quiz-view'),
    path('results/', result_view, name='result-view'),
    path("results/delete/<str:pk>/", delete_result, name='delete-quiz'),
    path("eval/<str:pk>/", eval_view, name='eval-view'),
    # path("render-pdf/", render_pdf_view, name='render-pdf-view'),
]

quizzes/models.py
from django.db import models

class Quiz(models.Model):
    # En tête
    FV_CHOICES = (
        ('Présentiel', 'Présentiel'),
        ('Visio', 'Visio'),
    )
    stage = models.CharField(choices=FV_CHOICES, max_length=200, null = True, blank = True)
    stage_name = models.CharField(max_length=200, null = True, blank = True)
    start_date = models.DateField(max_length=200, null = True, blank = True)
    end_date = models.DateField(max_length=200, null = True, blank = True)
    place = models.CharField(max_length=200, null = True, blank = True)
    teacher = models.CharField(max_length=200, null = True, blank = True)
    # Organisation
    organization1 = models.CharField(max_length=200, null = True, blank = True)
    org_comment1 = models.CharField(max_length=200, null = True, blank = True)
    organization2 = models.CharField(max_length=200, null = True, blank = True)
    org_comment2 = models.CharField(max_length=200, null = True, blank = True)
    organization3 = models.CharField(max_length=200, null = True, blank = True)
    org_comment3 = models.CharField(max_length=200, null=True, blank=True)
    # Formation
    formation1 = models.CharField(max_length=200, null = True, blank = True)
    for_comment1 = models.CharField(max_length=200, null=True, blank=True)
    formation2 = models.CharField(max_length=200, null = True, blank = True)
    for_comment2 = models.CharField(max_length=200, null=True, blank=True)
    formation3 = models.CharField(max_length=200, null = True, blank = True)
    for_comment3 = models.CharField(max_length=200, null=True, blank=True)
    formation4 = models.CharField(max_length=200, null = True, blank = True)
    for_comment4 = models.CharField(max_length=200, null=True, blank=True)
    formation5 = models.CharField(max_length=200, null = True, blank = True)
    for_comment5 = models.CharField(max_length=200, null=True, blank=True)
    formation6 = models.CharField(max_length=200, null = True, blank = True)
    for_comment6 = models.CharField(max_length=200, null=True, blank=True)
    # Formateur(s)
    teacher1 = models.CharField(max_length=200, null = True, blank = True)
    tea_comment1 = models.CharField(max_length=200, null=True, blank=True)
    teacher2 = models.CharField(max_length=200, null = True, blank = True)
    tea_comment2 = models.CharField(max_length=200, null=True, blank=True)
    teacher3 = models.CharField(max_length=200, null = True, blank = True)
    tea_comment3 = models.CharField(max_length=200, null=True, blank=True)
    teacher4 = models.CharField(max_length=200, null = True, blank = True)
    tea_comment4 = models.CharField(max_length=200, null=True, blank=True)
    # Appréciation générale
    appreciation1 = models.CharField(max_length=200, null = True, blank = True)
    ap_comment1 = models.CharField(max_length=200, null=True, blank=True)
    appreciation2 = models.CharField(max_length=200, null = True, blank = True)
    ap_comment2 = models.CharField(max_length=200, null=True, blank=True)
    # Recommandation de la formamtion
    recommendation1 = models.CharField(max_length=200, null = True, blank = True)
    recommendation2 = models.CharField(max_length=200, null = True, blank = True)
    # Autres besoins de la formation
    other_formation1 = models.CharField(max_length=200, null=True, blank=True)
    other_formation2 = models.CharField( max_length=200, null = True, blank = True)
    other_formation_comment = models.CharField(max_length=200, null=True, blank=True)
    # Types, autres besoins de la formation
    other_formation_type1 = models.CharField(max_length=200, null=True, blank=True)
    other_formation_type2 = models.CharField( max_length=200, null = True, blank = True)
    other_formation_type_comment = models.CharField(max_length=200, null = True, blank = True)
    # PARTICIPANT
    name = models.CharField(max_length=200, null=True, blank=True)
    function = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    company = models.CharField(max_length=200, null=True, blank=True)
    company_activity = models.CharField(max_length=200, null=True, blank=True)
    total_company = models.CharField(max_length=200, null=True, blank=True)
    total_establishment = models.CharField(max_length=200, null=True, blank=True)
    election_date = models.DateField(max_length=200, null = True, blank = True)
    # Comment avez-vous connu ce stage
    find = models.CharField( max_length=200, null=True, blank=True)
    find_comment = models.CharField(max_length=200, null=True, blank=True)
    # created
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

quizzes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Quiz


class DateInput(forms.DateInput):
    input_type = 'date'

class QuizForm(forms.ModelForm):
    EVAL_CHOICES = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
    )
    BOOL_CHOICES = (
        ('Oui', 'Oui'),
        ('Non', 'Non'),
    )
    CHECK_CHOICES = (
        ('CSE', 'CSE'),
        ('SSCT', 'SSCT'),
        ('Référent harcèlement', 'Référent harcèlement'),
        ('Représentant de proximité', 'Représentant de proximité'),
        ('DUERP', 'DUERP'),
        ('AUTRES', 'AUTRES'),
    )
    TYPE_CHOICES = (
        ('Assistance juridique', 'Assistance juridique'),
        ('Communication / négociation', 'Communication / négociation'),
        ('Expertise SSCT', 'Expertise SSCT'),
        ('Expertise comptable', 'Expertise comptable'),
        ('Autres', 'Autres'),
    )
    FIND_CHOICES = (
        ('Site internet', 'Site internet'),
        ('Mailing', 'Mailing'),
        ('Entreprise ayant déjà participé à un stage SICOGE', 'Entreprise ayant déjà participé à un stage SICOGE'),
        ('Autre', 'Autre'),
    )
    # Organisation
    organization1 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    organization2 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    organization3 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    # Formation
    formation1 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    formation2 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    formation3 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    formation4 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    formation5 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    formation6 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    # Formateur(s)
    teacher1 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    teacher2 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    teacher3 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    teacher4 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    # Appréciation générale
    appreciation1 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    appreciation2 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    # Recommandation de la formamtion
    recommendation1 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=BOOL_CHOICES,
    )
    # Autres besoins de la formation
    other_formation1 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=BOOL_CHOICES,
    )
    other_formation2 = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=CHECK_CHOICES,
    )
    # Types, autres besoins de la formation
    other_formation_type1 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=BOOL_CHOICES,
    )
    other_formation_type2 = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=TYPE_CHOICES,
    )
    # Comment avez-vous connu ce stage
    find = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=FIND_CHOICES,
    )
    class Meta:
        model = Quiz
        fields = '__all__'
        widgets = {
            'start_date': DateInput(attrs={'type': 'text'}),
            'end_date': DateInput(attrs={'type': 'text'}),
            'election_date': DateInput(attrs={'type': 'text'}),
            'stage': forms.RadioSelect,
        }

quizzes/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.db.models import Q
from django.core.paginator import Paginator
from .models import Quiz
from .forms import QuizForm

# To generate PDF white xhtml2pdf
# from django.http import HttpResponse
# from django.template.loader import get_template
# from xhtml2pdf import pisa
# from quizzes.utils import generate_pdf


# Create your views here.

def result_view(request):
    results = Quiz.objects.all()
    query = request.GET.get('qs', '')
    if query:
        queryset = (Q(stage__icontains=query)) | (Q(name__icontains=query)) | (Q(stage_name__icontains=query)) | (
            Q(start_date__icontains=query)) | (Q(teacher__icontains=query))
        results = Quiz.objects.filter(queryset).distinct()
    # paginator = Paginator(questions, 20)
    # page_number = request.GET.get('page')
    # page_obj = Paginator.get_page(paginator, page_number)
    context = {
        # 'page_obj': page_obj,
        'results': results,
    }
    return render(request, 'quizzes/result.html', context)

def delete_result(request, pk):
    quiz = Quiz.objects.get(id=pk)
    if request.method == "POST":
        quiz.delete()
        return redirect('quizzes:result-view')
    context = {
        'quiz': owner,
    }
    return render(request, 'quizzes/delete.html', context)

def quiz_view(request):
    form = QuizForm()
    if request.method == 'POST':
        form = QuizForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('quizzes:result-view')
    context = {
        'form': form,
    }
    return render(request, 'quizzes/quiz.html', context)

def eval_view(request, pk):
    """
    student eval pdf views
     """
    eval = get_object_or_404(Quiz, id=pk)
    # other_formations = list(eval.other_formation2)

    context = {
        # 'other_formations': other_formations,
        'eval': eval,
    }
    template_path = 'quizzes/eval.html'
    pdf_name = 'Evaluation'
    return render(request, template_path, context)
    # return generate_pdf(request, template_path, pdf_name, context)


# def render_pdf_view(request):
#     template_path = 'quizzes/pdf.html'
#     context = {'myvar': 'this is your template context'}
#     # Create a Django response object, and specify content_type as pdf
#     response = HttpResponse(content_type='application/pdf')
#     # if download:
#     # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
#     # if display:
#     response['Content-Disposition'] = 'filename="report.pdf"'
#     # find the template and render it.
#     template = get_template(template_path)
#     html = template.render(context)
#
#     # create a pdf
#     pisa_status = pisa.CreatePDF(
#        html, dest=response)
#     # if error then show some funy view
#     if pisa_status.err:
#        return HttpResponse('We had some errors <pre>' + html + '</pre>')
#     return response

quizzes/templates/quizzes/delete.html
<form method="POST" action="{% url 'quizzes:delete-quiz' quiz.pk %}">
  {% csrf_token %}
  <div class="modal-header card-header">
    <h2 class="modal-title">Suppression d'une evaluation de satisfaction</h2>
    <button type="button" class="add" data-bs-dismiss="modal" ><span class="las la-times"></span></button>
  </div>
  <div class="modal-body">
    <span>Êtes vous sûr de vouloir supprimer cette évaluation ? </span>
  </div>
  <div class="modal-footer form-btn modal-delete">
    <button type="button" class="cancel-btn" data-bs-dismiss="modal">Annuler</button>
    <button class="confirm-btn" type="submit" name="Confirm">Supprimer</button>
  </div>
</form>

quizzes/templates/quizzes/quiz_modal.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
<script src="{% static 'js/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}
<!-- Modal -->
<div class="modal fade" id="evaluationStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Commencer l'évaluation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body-confirm"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Non</button>
        <button type="button" id="start-button" class="btn btn-success">Oui</button>
      </div>
    </div>
  </div>
</div>


<div class="row mb-3">
  <div class="h1">Evaluation de satisfaction :</div>
  <div class="col text-right"><a href="{% url 'quizzes:eval-view'%}" class="btn btn-danger">+</a></div>
</div>
<hr>
{% for obj in page_obj %}
<!-- Button trigger modal -->
<button class="btn btn-link modal-button"
        data-pk="{{obj.pk}}"
        data-evaluation="{{obj.name}}"
        data-questions="{{obj.number_of_questions}}"
        data-toggle="modal"
        data-target="#evaluationStartModal"
>
  {{obj}}
</button>
<br>
{% endfor %}
{% endblock content %}

quizzes/templates/quizzes/result.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block scripts %}

{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}
    <div class="table-responsive">
      <table>
        <thead class="table-header">
        <tr>
          <th>Formation</th>
          <th>Réalisation</th>
          <th>Date début</th>
          <th>Date fin</th>
          <th>Lieu</th>
          <th>Formateur(s)</th>
          <th>Stagiaire</th>
          <th>Evaluation</th>
          <th>Supprimer</th>
        </tr>
        </thead>
        <tbody>
        {% for result in results %}
        <tr>
          <td>{{ result.stage_name }}</td>
          <td>{{ result.stage }}</td>
          <td>
            {% language 'fr' %}
            {{ result.start_date | date:'d-m-y'}}
            {% endlanguage %}
          </td>
          <td>
            {% language 'fr' %}
            {{ result.end_date | date:'d-m-y'}}
            {% endlanguage %}
          </td>
          <td>{{ result.place }}</td>
          <td>{{ result.teacher }}</td>
          {% if result.name %}
          <td>{{ result.name }}</td>
          {% else %}
          <td>--</td>
          {% endif %}
          <td>
            <a href="{% url 'quizzes:eval-view' result.id %}">
              <button class="export">Export pdf</button>
            </a>
          </td>
          <td>
          
          </td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock content %}